#! perl

# $Id$

# pragmata
use strict;
use warnings;
use 5.008;

use lib qw( . lib ../lib ../../lib ../../lib );

#use Parrot::Test::Harness language => 'smart',
#                          compiler => 'smart.pbc';

# use Smart::Test::Unit   path    => 't',
#                         files   => [ 't/gnu-make-compatibility/*.t' ],
#                         smart   => '../../parrot smart.pbc';
use Smart::Test::Unit   files   => [ 't/gnu-make-compatibility/*.t' ],
                        smart   => '../../parrot smart.pbc';

